CREATE MASTER KEY ENCRYPTION BY PASSWORD = '[PASSWORD]'
GO

CREATE DATABASE SCOPED CREDENTIAL BlobStorageCredential
	WITH IDENTITY = 'SHARED ACCESS SIGNATURE',	-- SAS token for Blob, Object, Read access (expires 8/13/2026)
	SECRET = '[SECRET]'
GO
